const fontList = [
    "Courier New",
"serif",
"sans-serif",
"monospace",
"cursive",
"fantasy",
"system-ui",
"ui-serif",
"math",
"fangsong",
"Kalam",
"Playwrite NG Modern",
"Playwrite NZ",
"Playwrite DE Grund",
"Ubuntu",
"Pacifico",
"Faster One",
"Shrikhand",
"Courgette",
"Martel",
"Yellowtail",
"Ubuntu Mono",
"Lobster Two",
"Merienda",
"Great Vibes",
"Concert One",
"Black Ops One",
"Amatic SC",
"Orbitron",
"Playwrite IN",
"Satisfy",
"Playwrite TZ",
"Indie Flower",
"Permanent Marker",
"Abril Fatface",
"Shadows Into Light",
"Tiny5",
"IBM Plex Mono",
"Caveat",
"Lobster",
"Chakra Petch",
"Playwrite IS",
"Playwrite FR Moderne",
"Playwrite RO",
"Playwrite NO",
"Playwrite AU TAS",
"Source Code Pro",
"Rubik Glitch Pop",
"Kode Mono",
"Dancing Script",
"Playwrite GB S",
"Margarine",
"Ga Maamli",
"Tangerine",
"Noto Sans Bengali",
"Rubik Bubbles",
"Jaini",
"Zeyada",
"Sacramento",
"Jacquard 12",
"VT323",
"Spicy Rice",
"Monoton",
"Audiowide",
"Honk",
"Allura",
"Cookie",
"Jersey 25 Charted",
"Jacquard 24 Charted",
"Tangerine",
"Architects Daughter",
"Special Elite",
"Jaini",
"Rubik Bubbles",
"Zeyada",
"Bangers",
"Danfo",
]

export default fontList